### ISSUE TITLE
Error during setup of component sensor

### ISSUE THREAD

**Issue by KingdomJnK** [robmarkcole/Hue-sensors-HASS#81]
i tried to hack my remote before, so I was excited to try this component but I keep getting this error  

Error during setup of component sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
AttributeError: module 'custom_components.sensor' has no attribute 'setup'Traceback (most recent call last):   File "/srv/homeassistant

**Comment by commandcontrolit** [comment]
I had the same issue after upgraded to 0.75.0 and trying to upgrade to the latest sensor. Neither worked out well and I had to restore to 0.74.0 and from a back up to get things working.

Did you ever manage to get this to work?

**Comment by digiltd** [comment]
Removing the empty _init_ file fixed it for me `custom_components/sensor/__init__.py`

I think the empty file was committed by mistake.

**Comment by KingdomJnK** [comment]
yes it works, thanks 
removing _init_.py did the trick
